# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  contentDir: content/en
  weight: 1
  languageName: English
  languageCode: en-us
  params:
    label: English
    locale: en-us

es:
  contentDir: content/es
  weight: 2
  title: CV Juan Hernández
  languageName: Español
  languageCode: es
  params:
    label: Español
    locale: es
    description: 'CV de Juan Hernández - Analista de Datos Clínicos y Optimización de Procesos'
