# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageName: English
  languageCode: en-us
  contentDir: content/en
  weight: 1

es:
  languageName: Español
  languageCode: es
  contentDir: content/es
  weight: 2
  title: CV Juan Hernández
  params:
    description: 'CV de Juan Hernández - Analista de Datos Clínicos y Optimización de Procesos'
